/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: User2005 (https://sketchfab.com/lorenzo.brewer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/phone-5c53e579e1ec49d0a68a380316c252dc
Title: Phone
*/
 
import  { useRef ,useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame , useThree } from '@react-three/fiber'
import  { a } from '@react-spring/three'
import PhoneScene from '../asset/3d/phone.glb'

const Phone =(props) => {
  const phoneRef = useRef();
  const { nodes, materials } = useGLTF(PhoneScene)
  return (
    <a.group ref={phoneRef} {...props} >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={12.08}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.037, 0.001, 0]} scale={[1, 3, 1]}>
            <mesh
              
              
              geometry={nodes.Object_6.geometry}
              material={materials.Silver}
            />
            <mesh
              
              
              geometry={nodes.Object_7.geometry}
              material={materials.Matt}
            />
            <mesh
              
              
              geometry={nodes.Object_8.geometry}
              material={materials.Matt_Black_Plastic}
            />
          </group>
          <group position={[0.059, 0.143, -0.005]} rotation={[Math.PI / 2, 0, 0]} scale={1.419}>
            <mesh
              
              
              geometry={nodes.Object_10.geometry}
              material={materials.Rubber}
            />
            <mesh
              
              
              geometry={nodes.Object_11.geometry}
              material={materials.Matt_Black_Plastic}
            />
            <mesh
              
              
              geometry={nodes.Object_12.geometry}
              material={materials.Phone_color}
            />
            <mesh
              
              
              geometry={nodes.Object_13.geometry}
              material={materials.Glass}
            />
          </group>
          <group position={[0.059, 0.126, -0.005]} rotation={[Math.PI / 2, 0, 0]} scale={1.743}>
            <mesh
              
              
              geometry={nodes.Object_15.geometry}
              material={materials.Black_Screen}
            />
            <mesh
              
              
              geometry={nodes.Object_16.geometry}
              material={materials.Phone_color}
            />
            <mesh
              
              
              geometry={nodes.Object_17.geometry}
              material={materials.Matt_Black_Plastic}
            />
            <mesh
              
              
              geometry={nodes.Object_18.geometry}
              material={materials.Glass}
            />
          </group>
          <group
            position={[0.046, 0.124, -0.005]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[2.696, 1.354, 2.696]}>
            <mesh
              
              
              geometry={nodes.Object_24.geometry}
              material={materials.Phone_color}
            />
            <mesh
              
              
              geometry={nodes.Object_25.geometry}
              material={materials['Material.004']}
            />
            <mesh
              
              
              geometry={nodes.Object_26.geometry}
              material={materials.Plastic_Glass}
            />
          </group>
          <group position={[0.037, 0.079, 0]}>
            <mesh
              
              
              geometry={nodes.Object_42.geometry}
              material={materials.Phone_color}
            />
            <mesh
              
              
              geometry={nodes.Object_43.geometry}
              material={materials.Black_Screen}
            />
          </group>
          <group position={[0.046, 0.135, -0.005]} rotation={[Math.PI / 2, 0, 0]} scale={1.419}>
            <mesh
              
              
              geometry={nodes.Object_61.geometry}
              material={materials.Rubber}
            />
            <mesh
              
              
              geometry={nodes.Object_62.geometry}
              material={materials.Matt_Black_Plastic}
            />
            <mesh
              
              
              geometry={nodes.Object_63.geometry}
              material={materials.Phone_color}
            />
            <mesh
              
              
              geometry={nodes.Object_64.geometry}
              material={materials.Glass}
            />
          </group>
          <mesh
            
            
            geometry={nodes.Object_4.geometry}
            material={materials.Matt_Black_Plastic}
            position={[0.037, 0.001, 0]}
          />
          <mesh
            
            
            geometry={nodes.Object_20.geometry}
            material={materials.Phone_color}
            position={[0.046, 0.144, -0.005]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={1.354}
          />
          <mesh
            
            
            geometry={nodes.Object_22.geometry}
            material={materials.material}
            position={[0.046, 0.144, -0.005]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={1.354}
          />
          <mesh
            
            
            geometry={nodes.Object_28.geometry}
            material={materials.Phone_color}
            position={[0.053, 0.135, -0.005]}
            scale={[1.047, 1.141, 1.141]}
          />
          <mesh
            
            
            geometry={nodes.Object_30.geometry}
            material={materials.Matt_Black_Plastic}
            position={[0.036, 0.154, 0.004]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.283}
          />
          <mesh
            
            
            geometry={nodes.Object_32.geometry}
            material={materials.Matt_Black_Plastic}
            position={[0.032, 0.158, 0]}
          />
          <mesh
            
            
            geometry={nodes.Object_34.geometry}
            material={materials.Matt_Black_Plastic}
            position={[0.018, 0.001, 0]}
            scale={[0.946, 1, 0.946]}
          />
          <mesh
            
            
            geometry={nodes.Object_36.geometry}
            material={materials.Phone_color}
            position={[0.037, 0.079, 0]}
            scale={[0.994, 1.003, 1]}
          />
          <mesh
            
            
            geometry={nodes.Object_38.geometry}
            material={materials.Phone_color}
            position={[0.074, 0.105, 0]}
            scale={[1, 1.033, 1]}
          />
          <mesh
            
            
            geometry={nodes.Object_40.geometry}
            material={materials.Rubber}
            position={[0.037, 0.079, 0]}
            scale={[0.994, 1.003, 1]}
          />
          <mesh
            
            
            geometry={nodes.Object_45.geometry}
            material={materials.Phone_color}
            position={[0.023, 0.158, 0]}
            scale={[1, 1, 0.712]}
          />
          <mesh

            geometry={nodes.Object_47.geometry}
            material={materials.Lems}
            position={[0.059, 0.143, -0.005]}
            scale={0.001}
          />
          <mesh
            geometry={nodes.Object_49.geometry}
            material={materials.Lems}
            position={[0.059, 0.143, -0.005]}
            scale={0.001}
          />
          <mesh
            geometry={nodes.Object_51.geometry}
            material={materials.Lems}
            position={[0.046, 0.135, -0.005]}
            scale={0.001}
          />
          <mesh           
            geometry={nodes.Object_53.geometry}
            material={materials.Lems}
            position={[0.046, 0.135, -0.005]}
            scale={0.001}
          />
          <mesh            
            geometry={nodes.Object_55.geometry}
            material={materials.Lems}
            position={[0.059, 0.126, -0.005]}
            scale={[0.002, 0.002, 0.001]}
          />
          <mesh                        
            geometry={nodes.Object_57.geometry}
            material={materials.Lems}
            position={[0.059, 0.126, -0.005]}
            scale={0.001}
          />
          <mesh
            geometry={nodes.Object_59.geometry}
            material={materials.Phone_color}
            position={[0, 0.112, 0]}
          />
        </group>
      </group>
    </a.group>
  );
}

export default Phone;
